### ISSUE TITLE
about evaluation

### ISSUE THREAD

**Issue by cschy** [ImKeTT/pcae#6]
Congratulations on your contribution to controlled text generation. The evaluation file evaluation.py is empty, could you provide it?

**Comment by cschy** [comment]
could you provide the classifier? any help would be appreciated.

**Comment by ImKeTT** [comment]
Sorry for the late reply, I dont have the access to my old server, thus am unable to provide the code of the classifier. 

Theoretically you can use any text classifier ([BERT](https://huggingface.co/bert-base-uncased), [RoBERTa](https://huggingface.co/roberta-base), etc. Huggingface has an excellent compatibility of those models) that finetuned on training texts to measure the control level of generated texts.

**Comment by ImKeTT** [comment]
I'll close this issue as completed if there're no further questions..
